apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: bank-app
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql:5.7
          command: ['sh', '-c', 
            'until mysql -h mysql-service -u $MYSQL_USER -p$MYSQL_PASSWORD -D bank_db -e "SELECT 1"; do echo "Waiting for MySQL"; sleep 5; done']
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: password
      containers:
        - name: app-container
          image: muhammadabdullahabrar/devops:bank-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom: 
                configMapKeyRef:
                  name: bank-app-config
                  key: spring_datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: bank-app-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: bank-app-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5